<a href="https://colab.research.google.com/github/NAGA-SAI-HANEESH/Numpy-u2club/blob/main/u2club.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PYTHON LIST METHODS**

In [ ]:
alist=[1,2,3,4,5,6,7,8,9,10]
alist.append(11)
print(alist)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
print(alist.pop())#pops up last element of list
alist.remove(3)#removing based on item
del(alist[5])#removes based on index
print(alist)

In [ ]:
alist.sort(reverse=True)
print(alist)
blist=alist.copy()
print(blist)


[6, 5, 4, 2, 1]
[6, 5, 4, 2, 1]


In [ ]:
clist=[1,2,1,2,1,3,4,1,5,6,6,6,7]
length=(clist.count(1))
print(length)

4


In [ ]:
clist.insert(3,0)
print(clist)

[1, 2, 1, 0, 2, 1, 3, 4, 1, 5, 6, 6, 6, 7]


In [ ]:
alphabets = ['a', 'e','i', 'o', 'g', 'l', 'i', 'u']
print(alphabets.index('i',3,7))

6


**PYTHON TUPLE METHODS**

In [ ]:
t=(1,2,3,4,5,6)
print(t)
print(type(t))
print(len(t))
print(max(t))
print(min(t))
print(t[1:3])
print(t[2])

(1, 2, 3, 4, 5, 6)
<class 'tuple'>
6
6
1
(2, 3)
3


In [ ]:
a=tuple()
a=(t*3)
print(a)
t=t+(7,11)
print(t)
y=(1,2,3)+(4,5)+(6,7)
print(y)

(1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6)
(1, 2, 3, 4, 5, 6, 7, 11)
(1, 2, 3, 4, 5, 6, 7)


In [ ]:
print(2 in t)
print(8 in t)

True
False


**PYTHON DICTIONARY METHODS**

In [ ]:
d={"physics": 23,
   "chemistry": 40,
   "maths": 30}
print(d)
print(type(d))

{'physics': 23, 'chemistry': 40, 'maths': 30}
<class 'dict'>


In [ ]:
d1 = d.copy()
print(d1)
d1.clear()
print(d1)

{'physics': 23, 'chemistry': 40, 'maths': 30}
{}


In [ ]:
print(d.get("physics"))
print(d.get(23))

23
None


In [ ]:
a=d.items()                                 #important this converts a dictionary into a list of tuples
print(a)
print(type(a))

dict_items([('physics', 23), ('chemistry', 40), ('maths', 30)])
<class 'dict_items'>


In [ ]:
b=d.keys()                                   # this gives only keys in dictionary which is returned as a list
print(b,type(b),sep='\n')

dict_keys(['physics', 'chemistry', 'maths'])
<class 'dict_keys'>


In [ ]:
c=d.values()                                 #this gives only values in dictionary which is returned as a list
print(c,type(c),sep='\n')

dict_values([23, 40, 30])
<class 'dict_values'>


**INSTALLING NUMPY PACKAGE**

In [ ]:
pip install numpy

**CREATING NUMPY ARRAYS**


In [ ]:
import numpy as np
array_a1=np.array([1,2,3,4,5])
print(array_a1)
array_a2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array_a2)

[1 2 3 4 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**DATA TYPES**

In [ ]:
array_b=np.array([1,2,3,4,6],dtype=np.float)
print(array_b)

[1. 2. 3. 4. 6.]


**SHAPE AND SIZE OF ARRAY**

In [ ]:
array_c=np.array([[1,2,3],[1,2,3.3]])
print(array_c)
print(array_c.shape)
print(array_c.size)

[[1.  2.  3. ]
 [1.  2.  3.3]]
(2, 3)
6


In [ ]:
seq1='haneesh'
seq2='sunil'
seq3='rahul'
array1=np.array([seq1,seq2,seq3])
print(array1)
print(array1.shape)
print(array1.size)

['haneesh' 'sunil' 'rahul']
(3,)
3


***RESHAPING***

In [ ]:
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr.size)
print(arr)
print(arr.reshape(7,2))#reshaping
print(arr.T)#transpose

14
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[ 1  8]
 [ 2  9]
 [ 3 10]
 [ 4 11]
 [ 5 12]
 [ 6 13]
 [ 7 14]]


**DIFFERENT TYPES OF ARRAYS FILLING**

In [ ]:
arraya=np.ones((4,4))
print(arraya)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arrayb=np.zeros((5,5))
print(arrayb)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arrayc=np.full((6,6),10 )
print(arrayc)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [ ]:
arrayd=np.random.random((3,3))
print(arrayd)

[[0.54303457 0.25752987 0.13304967]
 [0.8625266  0.89733948 0.50204377]
 [0.95524388 0.55660801 0.61025995]]


In [ ]:
arraye=np.arange(0,9,1)
print(arraye)

[0 1 2 3 4 5 6 7 8]


**INDEXING**

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a[0],a[1])
print(a[1,1])
print(a[-2,-1])

[1 2 3 4] [5 6 7 8]
6
12


**SLICING**

In [ ]:
#[start_rowno:end_rowno:slicing_rate,start_column:end_column:slicing_rate]
row1=['a','b','c','d','e','f']
row2=['g','h','i','j','k','l']
row3=['m','n','o','p','q','r']
row4=['s','t','u','v','w','x']
t=np.array([row1,row2,row3,row4])
print(t)
#print(t[1])
#print(t[:,2:4])
#print(t[1:4,:])
print(t[1:3,2:5])
#print(t[:,0:4:2])

[['a' 'b' 'c' 'd' 'e' 'f']
 ['g' 'h' 'i' 'j' 'k' 'l']
 ['m' 'n' 'o' 'p' 'q' 'r']
 ['s' 't' 'u' 'v' 'w' 'x']]
[['i' 'j' 'k']
 ['o' 'p' 'q']]


**BOOLEAN**

In [ ]:
c=np.array([[1,2,3,4,5],[10,11,12,13,14]])
print(c)
boolc=c<5
print(boolc)

bool_values_c=np.where(c<5,c,0)
print(bool_values_c)

bool2_values_c=np.logical_and(c>5,c<12)
print(bool2_values_c)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]
[[ True  True  True  True False]
 [False False False False False]]
[[1 2 3 4 0]
 [0 0 0 0 0]]
[[False False False False False]
 [ True  True False False False]]


**SINGLE ARRAY OPERATIONS**

In [ ]:
h=np.array([[1,2,3],[1,2,3]])
print(h)
print(h.sum(axis=0))#axis=0 is rows;axis=1 is colums
print(h.cumsum())
print(h.prod())
print(h.cumprod())
print(h.ptp(axis=0))#peak to peak ===range{max-min}
print(h.min(axis=1))
#print(h.max())
#print(h.mean())

[[1 2 3]
 [1 2 3]]
[2 4 6]
[ 1  3  6  7  9 12]
36
[ 1  2  6  6 12 36]
[0 0 0]


**TWO ARRAY OPERATIONS**

In [ ]:
h1=np.arange(1,11,1)
h=h1.reshape(2,5)
i1=np.arange(11,21,1)
i=i1.reshape(2,5)
print(h)
print(i)
print(h+i)
print(h-i)
print(h*i)
#print(h/i)
print(h//i)
#print(np.dot(h,i))#vector_dot_product
#print(np.power(h,i))
a1=np.array([[1,2,3],[1,2,3],[1,2,3]])
a2=a1.T
print(np.matmul(a1,a2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[12 14 16 18 20]
 [22 24 26 28 30]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[14 14 14]
 [14 14 14]
 [14 14 14]]
